title: "<Your Name>'s Blog"
description: "Outreachy application blog"
theme: minima
url: "https://<yourusername>.github.io"
timezone: "America/New_York"

# Enable RSS feed (GitHub Pages supports this plugin)
plugins:
  - jekyll-feed
